version: "3.9"

services:
  user-app:
    build:
      context: ./user-app
    ports:
      - "8001:8001"
    env_file:
      - ./user-app/.env
    volumes:
      - ./user-app:/app
      - ./Fast.db:/data/Fast.db  # Shared database file
    environment:
      - PYTHONPATH=/app

  item-app:
    build:
      context: ./item
    ports:
      - "8002:8002"
    env_file:
      - ./item/.env
    volumes:
      - ./item:/app  # Ensure the entire item directory is mapped to /app
      - ./Fast.db:/data/Fast.db  # Shared database file
    environment:
      - PYTHONPATH=/app

  order-app:
    build:
      context: ./order
    ports:
      - "8003:8003"
    env_file:
      - ./order/.env
    volumes:
      - ./order:/app
      - ./Fast.db:/data/Fast.db  # Shared database file
    environment:
      - PYTHONPATH=/app

volumes:
  user-app-data:
  item-app-data:
  order-app-data:  # Shared volume for the database
